---
language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'

env:
  matrix:
    - FLAGS="--prefer-lowest --prefer-stable"
    - FLAGS=""

before_install:
  - echo yes | pecl upgrade apcu
  - echo "apc.enabled=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "apc.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update && composer update $FLAGS

services:
  - redis

script: ./vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  - bash <(curl -s https://codecov.io/bash)
